[global]
# SQLite database (default)
db = "/mnt/dshield/data/db/cowrieprocessor.sqlite"

# PostgreSQL database (optional - requires: uv pip install -e ".[postgres]")
# db = "postgresql://user:password@localhost:5432/cowrie"
# db = "postgresql://user:password@postgres.example.com:5432/cowrie?sslmode=require"

report_dir = "/mnt/dshield/reports"

[[sensor]]
name = "honeypot-a"
logpath = "/mnt/dshield/a/NSM/cowrie"
summarizedays = 1
email = "you@example.com"
# Optional per-sensor override for report_dir
# report_dir = "/mnt/dshield/reports/honeypot-a"
#
# Secrets can be provided as plain values or secret references.
# Recommended: use secret references and let orchestrate_sensors set env vars.
# Examples:
# vtapi = "env:VT_API_KEY"                  # from environment
# vtapi = "op://Security/VirusTotal/api"    # 1Password item field
# urlhausapi = "aws-sm://us-east-1/urlhaus#api_key"  # AWS Secrets Manager
# spurapi = "vault://kv/data/spur#token"     # HashiCorp Vault KV v2
# email = "file:/run/secrets/dshield_email"   # From a file

[[sensor]]
name = "honeypot-b"
logpath = "/mnt/dshield/b/NSM/cowrie"
summarizedays = 1
